import type { ISellerTableRow } from "./SellerTableRow.vue";

export const sellersData: ISellerTableRow[] = [
  {
    id: 1,
    name: "Anthony S. Amaya",
    image: "/images/avatars/9.png",
    email: "antho.am@yahoo.com",
    gender: "male",
    sales: 20,
    earning: 350,
    date: "29 Mar 2024",
    verified: true,
    mobileNumber: "402-788-1602",
    shopName: "Urban Chic Boutique",
  },
  {
    id: 2,
    name: "Crystal R. Taylor",
    image: "/images/avatars/10.png",
    email: "crystal_taylor@hotmail.com",
    gender: "female",
    sales: 24,
    earning: 360,
    date: "29 Apr 2024",
    verified: false,
    mobileNumber: "469-632-2611",
    shopName: "Whimsical Wares Emporium",
  },
  {
    id: 3,
    name: "Jeremy M. Simon",
    image: "/images/avatars/7.png",
    email: "jer.sim@gmail.com",
    gender: "male",
    sales: 34,
    earning: 574,
    date: "29 Nov 2023",
    verified: true,
    mobileNumber: "207-538-1345",
    shopName: "Serene Styles Haven",
  },
  {
    id: 4,
    name: "Jane B. Bush",
    image: "/images/avatars/8.png",
    email: "jane@bush.com",
    gender: "female",
    sales: 54,
    earning: 487,
    date: "29 Jan 2024",
    verified: true,
    mobileNumber: "612-326-9186",
    shopName: "Posh Picks Boutique",
  },
  {
    id: 5,
    name: "Francis A. Bisson",
    image: "/images/avatars/5.png",
    email: "francis.biss@outlook.com",
    gender: "male",
    sales: 67,
    earning: 784,
    date: "29 Dec 2023",
    verified: true,
    mobileNumber: "317-949-1232",
    shopName: "Blissful Finds Co.",
  },
  {
    id: 6,
    name: "Lydia P. Barnett",
    image: "/images/avatars/6.png",
    email: "lydia.p@mail.com",
    gender: "female",
    sales: 74,
    earning: 657,
    date: "29 Jun 2023",
    verified: false,
    mobileNumber: "936-895-2100",
    shopName: "Trendy Threads Emporium",
  },
  {
    id: 7,
    name: "John B. Lopez",
    image: "/images/avatars/3.png",
    email: "john@lopez.com",
    gender: "male",
    sales: 45,
    earning: 354,
    date: "29 Jul 2023",
    verified: true,
    mobileNumber: "262-849-4319",
    shopName: "Luxe Loft Creations",
  },
  {
    id: 8,
    name: "Detra M. Rogers",
    image: "/images/avatars/4.png",
    email: "detra@rogers.com",
    gender: "female",
    sales: 21,
    earning: 352,
    date: "29 Dec 2023",
    verified: true,
    mobileNumber: "847-452-0238",
    shopName: "Vintage Vogue Hub",
  },
  {
    id: 9,
    name: "Antonio D. Goss",
    image: "/images/avatars/1.png",
    email: "goss@ant.com",
    gender: "male",
    sales: 29,
    earning: 920,
    date: "29 Apr 2023",
    verified: false,
    mobileNumber: "203-250-6265",
    shopName: "Coastal Charm Marketplace",
  },
  {
    id: 10,
    name: "Brenda R. Holmes",
    image: "/images/avatars/2.png",
    email: "brenda.holmes@mail.com",
    gender: "female",
    sales: 67,
    earning: 874,
    date: "29 Mar 2023",
    verified: true,
    mobileNumber: "325-480-1291",
    shopName: "Dapper Designs Depot",
  },
];
