import type { IProductTableRow } from "./ProductTableRow.svelte";

export const productsData: IProductTableRow[] = [
  {
    id: 1001,
    name: "Men's tracking shoes",
    image: "/images/apps/ecommerce/products/1.jpg",
    createdAt: "30 Nov 2024",
    category: "Fashion",
    price: 29,
    stock: 43,
    orders: 10,
    ratings: 4.7,
    ratingsCount: 130,
    sku: "SHOES",
  },
  {
    id: 1002,
    name: "Cocooil body oil",
    image: "/images/apps/ecommerce/products/2.jpg",
    createdAt: "30 Nov 2024",
    category: "Daily Need",
    price: 16,
    stock: 35,
    orders: 15,
    ratings: 4.2,
    ratingsCount: 547,
    sku: "COCOOIL",
  },
  {
    id: 1003,
    name: "Freeze air ",
    image: "/images/apps/ecommerce/products/3.jpg",
    createdAt: "30 Jul 2024",
    category: "Cosmetic",
    price: 32,
    stock: 43,
    orders: 25,
    ratings: 3.8,
    ratingsCount: 862,
    sku: "FREEAIR",
  },
  {
    id: 1004,
    name: "Ladies's shoes",
    image: "/images/apps/ecommerce/products/4.jpg",
    createdAt: "30 Jan 2024",
    category: "Fashion",
    price: 32,
    stock: 0,
    orders: 10,
    ratings: 2.9,
    ratingsCount: 861,
    sku: "LASHOES",
  },
  {
    id: 1005,
    name: "Gamepad",
    image: "/images/apps/ecommerce/products/5.jpg",
    createdAt: "30 Oct 2024",
    category: "Electronics",
    price: 59,
    stock: 48,
    orders: 42,
    ratings: 4.1,
    ratingsCount: 96,
    sku: "GAMEPAD",
  },
  {
    id: 1006,
    name: "Blue & Pink Clothes",
    image: "/images/apps/ecommerce/products/6.jpg",
    createdAt: "30 May 2024",
    category: "Fashion",
    price: 27,
    stock: 36,
    orders: 31,
    ratings: 4.24,
    ratingsCount: 72,
    sku: "BPCloth",
  },
  {
    id: 1007,
    name: "Ladies's shorts wear",
    image: "/images/apps/ecommerce/products/7.jpg",
    createdAt: "30 Sep 2024",
    category: "Fashion",
    price: 24,
    stock: 21,
    orders: 42,
    ratings: 3.5,
    ratingsCount: 48,
    sku: "LSWEAR",
  },
  {
    id: 1008,
    name: "Kitchen's Fruits & Vegetable",
    image: "/images/apps/ecommerce/products/8.jpg",
    createdAt: "30 Apr 2024",
    category: "Food",
    price: 45,
    stock: 12,
    orders: 36,
    ratings: 2.7,
    ratingsCount: 54,
    sku: "KFVEGE",
  },
  {
    id: 1009,
    name: "Quokka Lemon Water",
    image: "/images/apps/ecommerce/products/9.jpg",
    createdAt: "30 Dec 2024",
    category: "Food",
    price: 7,
    stock: 35,
    orders: 27,
    ratings: 4.1,
    ratingsCount: 64,
    sku: "QUOKKA",
  },
  {
    id: 1010,
    name: "White & Brown Candy",
    image: "/images/apps/ecommerce/products/10.jpg",
    createdAt: "30 Jun 2024",
    category: "Food",
    price: 14,
    stock: 0,
    orders: 42,
    ratings: 3.6,
    ratingsCount: 84,
    sku: "CANDY",
  },
  {
    id: 1011,
    name: "Yellow Ice cream",
    image: "/images/apps/ecommerce/products/11.jpg",
    createdAt: "30 Jan 2024",
    category: "Food",
    price: 15,
    stock: 26,
    orders: 31,
    ratings: 4.9,
    ratingsCount: 52,
    sku: "ICECREAM",
  },
];
