import type { IShopTableRow } from "./ShopTableRow.svelte";

export const shopsData: IShopTableRow[] = [
  {
    id: 1,
    sellerId: 1,
    sellerName: "Anthony S. Amaya",
    email: "urban.chic@yahoo.com",
    orders: 20,
    earning: 350,
    date: "29 Mar 2024",
    verified: true,
    mobileNumber: "402-788-1602",
    name: "Urban Chic Boutique",
    ratings: 4.4,
    ratingsCount: 124,
  },
  {
    id: 2,
    sellerId: 2,
    sellerName: "Crystal R. Taylor",
    email: "whimscal_ware@hotmail.com",
    orders: 24,
    earning: 360,
    date: "29 Apr 2024",
    verified: true,
    mobileNumber: "469-632-2611",
    name: "Whimsical Wares Emporium",
    ratings: 4.7,
    ratingsCount: 241,
  },
  {
    id: 3,
    sellerId: 3,
    sellerName: "Jeremy M. Simon",
    email: "serene.styles@gmail.com",
    orders: 34,
    earning: 574,
    date: "29 Nov 2023",
    verified: true,
    mobileNumber: "207-538-1345",
    name: "Serene Styles Haven",
    ratings: 4.2,
    ratingsCount: 104,
  },
  {
    id: 4,
    sellerId: 4,
    sellerName: "Jane B. Bush",
    email: "posh_picks@bush.com",
    orders: 54,
    earning: 487,
    date: "29 Jan 2024",
    verified: true,
    mobileNumber: "612-326-9186",
    name: "Posh Picks Boutique",
    ratings: 3.8,
    ratingsCount: 261,
  },
  {
    id: 5,
    sellerId: 5,
    sellerName: "Francis A. Bisson",
    email: "blissful_co@outlook.com",
    orders: 67,
    earning: 784,
    date: "29 Dec 2023",
    verified: false,
    mobileNumber: "317-949-1232",
    name: "Blissful Finds Co.",
    ratings: 3.4,
    ratingsCount: 195,
  },
  {
    id: 6,
    sellerId: 6,
    sellerName: "Lydia P. Barnett",
    email: "trendy_te@mail.com",
    orders: 74,
    earning: 657,
    date: "29 Jun 2023",
    verified: true,
    mobileNumber: "936-895-2100",
    name: "Trendy Threads Emporium",
    ratings: 4.6,
    ratingsCount: 135,
  },
  {
    id: 7,
    sellerId: 7,
    sellerName: "John B. Lopez",
    email: "luxe.loft@lopez.com",
    orders: 45,
    earning: 354,
    date: "29 Jul 2023",
    verified: true,
    mobileNumber: "262-849-4319",
    name: "Luxe Loft Creations",
    ratings: 4.9,
    ratingsCount: 321,
  },
  {
    id: 8,
    sellerId: 8,
    sellerName: "Detra M. Rogers",
    email: "vintage_hub@rogers.com",
    orders: 21,
    earning: 352,
    date: "29 Dec 2023",
    verified: true,
    mobileNumber: "847-452-0238",
    name: "Vintage Vogue Hub",
    ratings: 2.8,
    ratingsCount: 12,
  },
  {
    id: 9,
    sellerId: 9,
    sellerName: "Antonio D. Goss",
    email: "antonio_gross@ant.com",
    orders: 29,
    earning: 920,
    date: "29 Apr 2023",
    verified: false,
    mobileNumber: "203-250-6265",
    name: "Coastal Charm Marketplace",
    ratings: 3.4,
    ratingsCount: 238,
  },
  {
    id: 10,
    sellerId: 10,
    sellerName: "Brenda R. Holmes",
    email: "dapper.designs@mail.com",
    orders: 67,
    earning: 874,
    date: "29 Mar 2023",
    verified: true,
    mobileNumber: "325-480-1291",
    name: "Dapper Designs Depot",
    ratings: 4.1,
    ratingsCount: 541,
  },
];
