import type { ICustomerTableRow } from "./CustomerTableRow.vue";

export const customersData: ICustomerTableRow[] = [
  {
    id: 1,
    name: "James S. Jackson",
    image: "/images/avatars/1.png",
    email: "james.jack@mail.com",
    gender: "male",
    purchases: 24,
    spend: 405,
    date: "29 Mar 2024",
    verified: true,
    mobileNumber: "845-346-8004",
  },
  {
    id: 2,
    name: "Nancy J. Schlueter",
    image: "/images/avatars/2.png",
    email: "nancy.schlueter@mail.com",
    gender: "female",
    purchases: 21,
    spend: 630,
    date: "29 Apr 2024",
    verified: true,
    mobileNumber: "703-776-8514",
  },
  {
    id: 3,
    name: "Anthony J. Lew",
    image: "/images/avatars/3.png",
    email: "anthony_lew@mail.com",
    gender: "male",
    purchases: 68,
    spend: 1241,
    date: "29 Nov 2023",
    verified: false,
    mobileNumber: "864-215-2686",
  },
  {
    id: 4,
    name: "Amanda M. Kyle",
    image: "/images/avatars/4.png",
    email: "amanda_kyle@mail.com",
    gender: "female",
    purchases: 43,
    spend: 648,
    date: "29 Jan 2024",
    verified: true,
    mobileNumber: "253-565-3114",
  },
  {
    id: 5,
    name: "Chad J. Pipkin",
    image: "/images/avatars/5.png",
    email: "chadpip007@mail.com",
    gender: "male",
    purchases: 17,
    spend: 357,
    date: "29 Dec 2023",
    verified: false,
    mobileNumber: "562-212-5847",
  },
  {
    id: 6,
    name: "Crystal P. Deberry",
    image: "/images/avatars/6.png",
    email: "crystal_deberry@mail.com",
    gender: "female",
    purchases: 49,
    spend: 354,
    date: "29 Jun 2023",
    verified: true,
    mobileNumber: "520-398-7428",
  },
  {
    id: 7,
    name: "Herman K. Byard",
    image: "/images/avatars/7.png",
    email: "herman_byard@mail.com",
    gender: "male",
    purchases: 47,
    spend: 358,
    date: "29 Jul 2023",
    verified: true,
    mobileNumber: "248-376-5482",
  },
  {
    id: 8,
    name: "Patricia T. Gandy",
    image: "/images/avatars/8.png",
    email: "pat.gandy@mail.com",
    gender: "female",
    purchases: 78,
    spend: 1547,
    date: "29 Dec 2023",
    verified: true,
    mobileNumber: "707-237-9941",
  },
  {
    id: 9,
    name: "James J. Herron",
    image: "/images/avatars/9.png",
    email: "james@mail.com",
    gender: "male",
    purchases: 54,
    spend: 1080,
    date: "29 Apr 2023",
    verified: true,
    mobileNumber: "262-726-6322",
  },
  {
    id: 10,
    name: "Gladys J. Tudor",
    image: "/images/avatars/10.png",
    email: "tudor_jgladys@mail.com",
    gender: "female",
    purchases: 48,
    spend: 1280,
    date: "29 Mar 2023",
    verified: true,
    mobileNumber: "508-975-1756",
  },
];
