import type { IOrderTableRow } from "./OrderTableRow.vue";

export const ordersData: IOrderTableRow[] = [
  {
    id: 21001,
    itemsCount: 5,
    customerName: "Emily Johnson",
    totalAmount: 342,
    paymentStatus: "paid",
    orderStatus: "Ordered",
    orderDate: "29 May 2024",
  },
  {
    id: 21002,
    itemsCount: 3,
    customerName: "Alex Thompson",
    totalAmount: 578,
    paymentStatus: "paid",
    orderStatus: "Accepted",
    orderDate: "29 Sep 2023",
  },
  {
    id: 21003,
    itemsCount: 6,
    customerName: "Sarah Davis",
    totalAmount: 215,
    paymentStatus: "pending",
    orderStatus: "On the Way",
    orderDate: "29 Jan 2024",
  },
  {
    id: 21004,
    itemsCount: 2,
    customerName: "Michael Wilson",
    totalAmount: 769,
    paymentStatus: "pending",
    orderStatus: "Delivered",
    orderDate: "29 Jul 2023",
  },
  {
    id: 21005,
    itemsCount: 7,
    customerName: "Jessica Miller",
    totalAmount: 431,
    paymentStatus: "paid",
    orderStatus: "Accepted",
    orderDate: "29 Apr 2024",
  },
  {
    id: 21006,
    itemsCount: 1,
    customerName: "Brian Anderson",
    totalAmount: 622,
    paymentStatus: "paid",
    orderStatus: "Ordered",
    orderDate: "29 Nov 2023",
  },
  {
    id: 21007,
    itemsCount: 4,
    customerName: "Olivia Smith",
    totalAmount: 894,
    paymentStatus: "pending",
    orderStatus: "On the way",
    orderDate: "29 Mar 2024",
  },
  {
    id: 21008,
    itemsCount: 7,
    customerName: "Daniel Robinson",
    totalAmount: 156,
    paymentStatus: "paid",
    orderStatus: "Delivered",
    orderDate: "29 Oct 2023",
  },
  {
    id: 21009,
    itemsCount: 1,
    customerName: "Emma Garcia",
    totalAmount: 497,
    paymentStatus: "pending",
    orderStatus: "Ordered",
    orderDate: "29 Jun 2024",
  },
  {
    id: 21010,
    itemsCount: 3,
    customerName: "Christopher Baker",
    totalAmount: 783,
    paymentStatus: "paid",
    orderStatus: "Accepted",
    orderDate: "29 Dec 2023",
  },
];
